language: go

go:
  - 1.8.x
  
install:
  - go get -v github.com/revel/revel/...
  - go get -v github.com/revel/cmd/revel
  - go get -v github.com/nu7hatch/gouuid

script:
  - revel test github.com/natejenson/go-api
